todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path('', views.home, name="home"),
    path('create/', views.create, name="create"),
    path('check/<int:id>', views.check, name="check"),
]

users/urls.py
from django.urls import path
from . import views
# '/users/' => 홈페이지
urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
]

todos/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Todo(models.Model):
    content = models.TextField()
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

users/models.py
from django.db import models

# Create your models here.

todos/views.py
from django.shortcuts import render, redirect
from .models import Todo
from django.contrib.auth.models import User
# Create your views here.
def home(request):
    # todos에 있는 내용을 다 가져와 보여주기

    todos = request.user.todo_set.all()
    context = {
        'todos': todos
    }
    return render(request, 'todos/home.html', context)

def create(request):
    # todos 작성하기
    content = request.POST.get('content')
    user_id = request.user.id
    # completed = request.POST.get('completed')
    # 현재 접속해 있는 유저의 아이디
    Todo.objects.create(content=content, user_id=user_id)


    return redirect('todos:home')

def check(request, id):
    # 특정 id를 가진 투두를 뽑아 completed = True
    todo = Todo.objects.get(pk=id)
    todo.completed = False if todo.completed else True
    todo.save()
    return redirect('todos:home')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
# Create your views here.
# '/users/' => 홈페이지
# '/users/login' => 로그인 화면

def home(request):
    return render(request, 'users/home.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # 1. 사용자가 로그인 되었을때
            messages.success(request, "성공적으로 로그인 되었습니다.")
            return redirect('todos:home')
        else:
            # 2. 사용자가 로그인이 되지 않았을때
            messages.success(request, "로그인이 되지 않았습니다. 다시 시도해 주세요.")
            return redirect('login')
    else:
        return render(request, 'users/login.html')

def logout_user(request):
    # 유저를 로그아웃 시킨다.
    logout(request)
    # 유저에게 로그아웃이 되었다는 메세지를 전달한다.
    messages.success(request, "성공적으로 로그아웃 되었습니다.")
    return redirect('todos:home')

todos/templates/todos/home.html
{% extends 'users/base.html' %}

{% block content %}
    <h1>Todo List</h1>
    <form action="/create/" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input name="content" type="text" class="form-control">
        </div>
        <div class="form-group">
            <button class="btn btn-primary">만들기</button>
        </div>
    </form>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">내용</th>
            <th scope="col">체크</th>
          <th scope="col">삭제</th>
        </tr>
      </thead>
      <tbody>
          {% for todo in todos %}
              <tr>
                  <th scope="row">{{ todo.user.email }}</th>
                  {% if todo.completed %}
                      <td><strike>{{ todo.content }}</strike></td>
                  {% else %}
                      <td>{{ todo.content }}</td>
                  {% endif %}

                  <td><button class="btn btn-dark"><a href="{% url 'todos:check' todo.id %}">체크</a></button></td>
                  <td>삭제</td>
              </tr>
          {% endfor %}

      </tbody>
    </table>


{% endblock %}

users/templates/users/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">TODO APP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                  </li>
            {% endif %}



        </ul>

      </div>
    </nav>

    {% if messages %}
        {% for message in messages %}

            <div class="alert alert-warning alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endfor %}
    {% endif %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}

{% block content %}
    <h1 class="text-center">Welcome to TODO APP</h1>
    {% if user.is_authenticated %}
        <p>이름 : {{ user.first_name }} {{ user.last_name }}</p>
        <p>이메일 : {{ user.email }}</p>
        <p>아이디 : {{ user.username }}</p>
        <p>비밀번호 : {{ user.password }}</p>
    {% endif %}

{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="col-md-6 offset-md-3">
        <h1 class="text-center">로그인</h1>
        <form method="POST" action="{% url 'login' %}">
            {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputEmail1">Username</label>
            <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

{% endblock %}